LUNA_NAME = "luna"
EMPTY_STRING = ""
HOME_DIRECTORY = "C:\\Users\\adama"
GOOGLE_QUERY_BASE = "https://google.com/search?query="
LUNA_MODEL_FILE = "luna-test.obj"

REDIS_EAR_CHANNEL = "ear-channel"
REDIS_EYE_CHANNEL = "eye-channel"
REDIS_MOUTH_CHANNEL = "mouth-channel"
REDIS_COMMAND_CHANNEL = "command-channel"
REDIS_EAR_SERVICE_CHANNEL = "ear-service-channel"


# Auto Hot Key Constants
MUTE_KEY = "Volume_Mute"
VOLUME_UP_KEY = "Volume_Up"
VOLUME_DOWN_KEY = "Volume_Down"
STOP_KEY_NAME = "Media_Stop"
PLAY_PAUSE_KEY = "Media_Play_Pause"
NEXT_KEY_NAME = "Media_Next"
PREV_KEY_NAME = "Media_Prev"

LEFT_CONTROL_KEY = "LCtrl"
RIGHT_CONTROL_KEY = "RCtrl"
CONTROL_KEY = "Ctrl"
LEFT_SHIFT_KEY = "LShift"
RIGHT_SHIFT_KEY = "RShift"
SHIFT_KEY = "Shift"
LEFT_ALT_KEY = "LAlt"
RIGHT_ALT_KEY = "RAlt"
ALT_KEY = "Alt"
LEFT_WIN_KEY = "LWin"
RIGHT_WIN_KEY = "RWin"
CAPS_KEY = "CapsLock"
SPACE_KEY = "Space"
TAB_KEY = "Tab"
ENTER_KEY = "Enter"
ESC_KEY = "Esc"
BACKSPACE_KEY = "Backspace"

UP_KEY = "Up"
DOWN_KEY = "Down"
LEFT_KEY = "Left"
RIGHT_KEY = "Right"

SCROLL_LOCK_KEY = "ScrollLock"
DEL_KEY = "Delete"
INSERT_KEY = "Insert"
HOME_KEY = "Home"
END_KEY = "End"
PAGE_UP_KEY = "PgUp"
PAGE_DOWN_KEY = "PgDn"
